### ISSUE TITLE
Attribute Name of PlantParent Joel in seeds.rb

### ISSUE THREAD

**Issue by astronaut-nemo** [learn-co-curriculum/phase-3-ar-more-models-practice#3]
In the file `lecture_kit/db/seed.rb` line 29, the attribute name is `person_id` instead of `plant_parent_id`.
That is:
https://github.com/learn-co-curriculum/phase-3-ar-more-models-practice/blob/0344898b18115ce565e04fbc5b9223fe1ce56057/lecture_kit/db/seeds.rb#L29

, which should be:

`PlantParenthood.create(plant_id: prayer_plant.id, plant_parent_id: joel.id, affection:0)`

This results in the error below when seeding the database:
> "ActiveModel::UnknownAttributeError: unknown attribute 'person_id' for PlantParenthood."

**Comment by lizbur10** [comment]
Thanks for bringing this to our attention @astronaut-nemo ! It has now been fixed 💙

**Comment by astronaut-nemo** [comment]
@lizbur10 Happy to help. Thank you for the amazing content.
